version: '3.8'

services:
  ezports-backend:
    container_name: ezports-backend
    image: ezports-backend
    build: 
      context: ./
      dockerfile: ./test-server.dockerfile
    ports:
      - ${SERVER_PORT}:8080
    restart: unless-stopped
    environment:
      DB_URL: ${DB_URL}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      NAVER_MAIL_PASSWORD: ${NAVER_MAIL_PASSWORD}
      SERVER_URL: ${SERVER_URL}