spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testDB?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: ${MYSQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000