spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  datasource:
    url: ${DB_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create-drop
        default_batch_fetch_size: 1000
---
auth:
  jwt:
    secretKey: ${JWT_SECRET_KEY}
    accessExp: 3600
    refreshExp: 592000
---
naver:
  mail:
    password: ${NAVER_MAIL_PASSWORD}
